<a href="https://colab.research.google.com/github/tariqzia5/Python_P/blob/main/Numpy_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
income=x.array([1200,1300,1400,1500,1600,1700])

In [ ]:
print(type(income))

<class 'numpy.ndarray'>


In [ ]:
income1=[2000,3000,4000]

In [ ]:
income1_arrray=np.array(income1)

In [ ]:
print(type(income1_arrray))

<class 'numpy.ndarray'>


# What is the difference between list and array

In [ ]:
list1=[1,2,3]
list2=[4,5,6]

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [ ]:
arr1+arr2

array([5, 7, 9])

In [ ]:
list1+list2

[1, 2, 3, 4, 5, 6]

## Another importane difference between list and array

In [ ]:
a=np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a1=np.array([1,2,3,4,'a'])

In [ ]:
a1

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [ ]:
income=np.array([1200,1300,1400,1500,1600,1700])

In [ ]:
expenses=income*0.5

In [ ]:
expenses

array([600., 650., 700., 750., 800., 850.])

In [ ]:
savings=income-expenses

In [ ]:
savings

array([600., 650., 700., 750., 800., 850.])

# N-Dimensional Arrays

In [ ]:
a=np.array([12,24,45,56])

In [ ]:
array_2=np.array([[12,23,45],[34,56,67]])
array_2

array([[12, 23, 45],
       [34, 56, 67]])

In [ ]:
array_3=np.array([[[1,2,3,4,5]]])

In [ ]:
array_3.ndim

3

# How to know the size,shape and dimension of the array

In [ ]:
#How to see the shape
a.shape

(4,)

In [ ]:
array_2.shape

(2, 3)

In [ ]:
#How to get the size of array
array_2.size

6

In [ ]:
#How to get the dimension of array
array_2.ndim

2

# Real time use of arrays

In [ ]:
import pandas as pd
bank=pd.read_csv("https://raw.githubusercontent.com/venkatareddykonasani/Datasets/master/Bank%20Tele%20Marketing/bank_market.csv")

In [ ]:
bank

Cust_num  age           job   marital  education default  balance  \
0             1   58    management   married   tertiary      no     2143   
1             2   44    technician    single  secondary      no       29   
2             3   33  entrepreneur   married  secondary      no        2   
3             4   47   blue-collar   married    unknown      no     1506   
4             5   33       unknown    single    unknown      no        1   
...         ...  ...           ...       ...        ...     ...      ...   
45206     45207   51    technician   married   tertiary      no      825   
45207     45208   71       retired  divorced    primary      no     1729   
45208     45209   72       retired   married  secondary      no     5715   
45209     45210   57   blue-collar   married  secondary      no      668   
45210     45211   37  entrepreneur   married  secondary      no     2971   

      housing loan    contact  day month  duration  campaign  pdays  previous  \
0         yes   no    unknown    5   may       261         1     -1         0   
1         yes   no    unknown    5   may       151         1     -1         0   
2         yes  yes    unknown    5   may        76         1     -1         0   
3         yes   no    unknown    5   may        92         1     -1         0   
4          no   no    unknown    5   may       198         1     -1         0   
...       ...  ...        ...  ...   ...       ...       ...    ...       ...   
45206      no   no   cellular   17   nov       977         3     -1         0   
45207      no   no   cellular   17   nov       456         2     -1         0   
45208      no   no   cellular   17   nov      1127         5    184         3   
45209      no   no  telephone   17   nov       508         4     -1         0   
45210      no   no   cellular   17   nov       361         2    188        11   

      poutcome    y  
0      unknown   no  
1      unknown   no  
2      unknown   no  
3      unknown   no  
4      unknown   no  
...        ...  ...  
45206  unknown  yes  
45207  unknown  yes  
45208  success  yes  
45209  unknown   no  
45210    other   no  

[45211 rows x 18 columns]

In [ ]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Cust_num   45211 non-null  int64 
 1   age        45211 non-null  int64 
 2   job        45211 non-null  object
 3   marital    45211 non-null  object
 4   education  45211 non-null  object
 5   default    45211 non-null  object
 6   balance    45211 non-null  int64 
 7   housing    45211 non-null  object
 8   loan       45211 non-null  object
 9   contact    45211 non-null  object
 10  day        45211 non-null  int64 
 11  month      45211 non-null  object
 12  duration   45211 non-null  int64 
 13  campaign   45211 non-null  int64 
 14  pdays      45211 non-null  int64 
 15  previous   45211 non-null  int64 
 16  poutcome   45211 non-null  object
 17  y          45211 non-null  object
dtypes: int64(8), object(10)
memory usage: 6.2+ MB


In [ ]:
age_var=np.array(bank["age"])

In [ ]:
type(age_var)

numpy.ndarray

In [ ]:
age_var.ndim

1

In [ ]:
age_var.size

45211

## Indexing in 1D arrays

In [ ]:
age_var[0]

58

In [ ]:
age_var[-1]

37

In [ ]:
age_var[[0,2,5]]

array([58, 33, 35])

In [ ]:
#Another way to do multiple indexing
x=[0,2,5]

In [ ]:
age_var[x]

array([58, 33, 35])

In [ ]:
age_var[-3:]

array([72, 57, 37])

In [ ]:
age_var[:]

array([58, 44, 33, ..., 72, 57, 37])

In [ ]:
age_var[:10]

array([58, 44, 33, 47, 33, 35, 28, 42, 58, 43])

# Advance indexing

In [ ]:
two_var=np.array(bank[["age","balance"]])

In [ ]:
print(two_var)

[[  58 2143]
 [  44   29]
 [  33    2]
 ...
 [  72 5715]
 [  57  668]
 [  37 2971]]


In [ ]:
two_var.shape

(45211, 2)

In [ ]:
two_var.size

90422

In [ ]:
two_var.ndim

2

In [ ]:
#indexing of 2-D arrays
two_var[0,0]

58

In [ ]:
two_var[1,1]

29

In [ ]:
#How to get last row element of 2nd column
two_var[-1,1]

2971

In [ ]:
#Slicing of 2-D array
two_var[:,:]

array([[  58, 2143],
       [  44,   29],
       [  33,    2],
       ...,
       [  72, 5715],
       [  57,  668],
       [  37, 2971]])

In [ ]:
two_var

array([[  58, 2143],
       [  44,   29],
       [  33,    2],
       ...,
       [  72, 5715],
       [  57,  668],
       [  37, 2971]])

In [ ]:
two_var[0:2,0:2]

array([[  58, 2143],
       [  44,   29]])

# Boolean Indexing

In [ ]:
age_var

array([58, 44, 33, ..., 72, 57, 37])

In [ ]:
#Suppose someone tell you to extract all those age which are less than 50
condition=age_var<50
condition

array([False,  True,  True, ..., False, False,  True])

In [ ]:
new_age=age_var[condition]

In [ ]:
new_age

array([44, 33, 47, ..., 23, 25, 37])

In [ ]:
print(age_var.shape)
print(new_age.shape)

(45211,)
(35017,)


In [ ]:
new_age1=age_var[condition==False]

In [ ]:
new_age1.shape

(10194,)

## Use of where statement in array

In [ ]:
age=np.array([-12,-34,54,23,67,87])

In [ ]:
age

array([-12, -34,  54,  23,  67,  87])

In [ ]:
#Please change all those age which are negative to 0 and rest to 1
age_new=np.where((age<0),0,1)

In [ ]:
age_new

array([0, 0, 1, 1, 1, 1])

In [ ]:
#please change all those age which are negative to 0 and rest keep it as it is.
age_new=np.where((age<0),0,age)


In [ ]:
age_new

array([ 0,  0, 54, 23, 67, 87])

# Lab2: accessing Arrays

In [ ]:
a=np.array([[1,2,3,4],[4,4,5,6],[8,9,19,11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
b=a[0:2,1:3]
b

array([[2, 3],
       [4, 5]])

In [ ]:
b[0,0]=45

In [ ]:
b

array([[45,  3],
       [ 4,  5]])

In [ ]:
a

array([[ 1, 45,  3,  4],
       [ 4,  4,  5,  6],
       [ 8,  9, 19, 11]])

In [ ]:
b=np.array(a[0:2,1:3],copy=False)

In [ ]:
b

array([[2, 3],
       [4, 5]])

In [ ]:
b[0,0]=54

In [ ]:
a

array([[ 1, 54,  3,  4],
       [ 4,  4,  5,  6],
       [ 8,  9, 19, 11]])

# Initial placeholders

In [ ]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
b=np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
c=b*2
c

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
b=np.ones((3,4),dtype=np.int32)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

# Arange Function

In [ ]:
a=np.arange(10,30,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
a=np.arange(10,30)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [ ]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
d=np.arange(-12.5,34,1.8)
d

array([-12.5, -10.7,  -8.9,  -7.1,  -5.3,  -3.5,  -1.7,   0.1,   1.9,
         3.7,   5.5,   7.3,   9.1,  10.9,  12.7,  14.5,  16.3,  18.1,
        19.9,  21.7,  23.5,  25.3,  27.1,  28.9,  30.7,  32.5])

# Linspace function

In [ ]:
a=np.linspace(10,30,5)
a

array([10., 15., 20., 25., 30.])

In [ ]:
a=np.linspace(10,30,7)
a

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        ])

In [ ]:
a=np.linspace(10,30,7,dtype=np.int32)
a

array([10, 13, 16, 20, 23, 26, 30], dtype=int32)

# Generating random numbers in arrays

In [ ]:
a=np.random.random(30)
a

array([0.6717378 , 0.90823741, 0.81459345, 0.97506103, 0.70401327,
       0.62044733, 0.11434647, 0.43654613, 0.94374674, 0.55892222,
       0.0423124 , 0.3883367 , 0.11329048, 0.07939481, 0.95708001,
       0.20464258, 0.07876181, 0.68900632, 0.33878026, 0.13115019,
       0.68551465, 0.53678063, 0.44647785, 0.85172355, 0.73614145,
       0.99591895, 0.78236048, 0.99926874, 0.5269487 , 0.70930562])

In [ ]:
rand_arr=np.random.random((5,3))
rand_arr

array([[0.60305566, 0.33825031, 0.73311869],
       [0.4467819 , 0.4172735 , 0.6767225 ],
       [0.96279276, 0.67829083, 0.61172163],
       [0.390851  , 0.52418589, 0.27720528],
       [0.41722536, 0.20851765, 0.70521   ]])

In [ ]:
rounded_arr=np.round(rand_arr,2)
rounded_arr

array([[0.6 , 0.34, 0.73],
       [0.45, 0.42, 0.68],
       [0.96, 0.68, 0.61],
       [0.39, 0.52, 0.28],
       [0.42, 0.21, 0.71]])

In [ ]:
#How to reshape the array
a=np.random.random(30)
a

array([0.80785175, 0.58131278, 0.72906818, 0.75609448, 0.13320948,
       0.86638465, 0.43579099, 0.84328045, 0.40068294, 0.56445304,
       0.46918945, 0.73970964, 0.58568796, 0.49889987, 0.10306603,
       0.19591591, 0.1670516 , 0.26980208, 0.07499145, 0.6524356 ,
       0.72043186, 0.10405595, 0.74168586, 0.90001417, 0.77837202,
       0.52918205, 0.62691103, 0.42167435, 0.10604021, 0.18339701])

In [ ]:
b=a.reshape(5,6)
b

array([[0.80785175, 0.58131278, 0.72906818, 0.75609448, 0.13320948,
        0.86638465],
       [0.43579099, 0.84328045, 0.40068294, 0.56445304, 0.46918945,
        0.73970964],
       [0.58568796, 0.49889987, 0.10306603, 0.19591591, 0.1670516 ,
        0.26980208],
       [0.07499145, 0.6524356 , 0.72043186, 0.10405595, 0.74168586,
        0.90001417],
       [0.77837202, 0.52918205, 0.62691103, 0.42167435, 0.10604021,
        0.18339701]])

In [ ]:
b=a.reshape(5,-1)
b

array([[0.03136202, 0.81229243, 0.75638635, 0.68265801, 0.61599107,
        0.9550052 ],
       [0.06958037, 0.81651959, 0.02008918, 0.0937618 , 0.24578876,
        0.19479034],
       [0.61933187, 0.15582091, 0.84819266, 0.10278916, 0.06098002,
        0.66891157],
       [0.51766081, 0.17011432, 0.74945168, 0.88674909, 0.10280986,
        0.75451718],
       [0.34991668, 0.6315643 , 0.20535439, 0.38787479, 0.57930546,
        0.72447842]])

In [ ]:
a=np.random.random(30)
a

array([0.03136202, 0.81229243, 0.75638635, 0.68265801, 0.61599107,
       0.9550052 , 0.06958037, 0.81651959, 0.02008918, 0.0937618 ,
       0.24578876, 0.19479034, 0.61933187, 0.15582091, 0.84819266,
       0.10278916, 0.06098002, 0.66891157, 0.51766081, 0.17011432,
       0.74945168, 0.88674909, 0.10280986, 0.75451718, 0.34991668,
       0.6315643 , 0.20535439, 0.38787479, 0.57930546, 0.72447842])

In [ ]:
b=a.reshape(-1,-1)
b

ValueError: ignored

In [ ]:
b=a.reshape(4,7)
b

ValueError: ignored

# Flatten Function

In [ ]:
a=np.random.random(10)
a

array([0.66041727, 0.42468486, 0.02887957, 0.56623135, 0.35681751,
       0.66140663, 0.92165986, 0.0212399 , 0.47841187, 0.36417014])

In [ ]:
b=a.reshape(5,2)
b

array([[0.66041727, 0.42468486],
       [0.02887957, 0.56623135],
       [0.35681751, 0.66140663],
       [0.92165986, 0.0212399 ],
       [0.47841187, 0.36417014]])

In [ ]:
b=b.flatten()
b

array([0.66041727, 0.42468486, 0.02887957, 0.56623135, 0.35681751,
       0.66140663, 0.92165986, 0.0212399 , 0.47841187, 0.36417014])

# Minimum and maximum of arrays

In [ ]:
age_var

array([58, 44, 33, ..., 72, 57, 37])

In [ ]:
age_var.min()

18

In [ ]:
min(age_var)

18

In [ ]:
age_subset=age_var[0:10]
age_subset

array([58, 44, 33, 47, 33, 35, 28, 42, 58, 43])

In [ ]:
age_subset.min()

28

In [ ]:
age_subset.max()

58

In [ ]:
age_subset.mean()

42.1

In [ ]:
age_subset.std()

9.741149829460586

In [ ]:
a.max()


0.991688400925843

In [ ]:
a.min()

0.0172151185554561

In [ ]:
a.max(axis=0)

array([0.9916884 , 0.9286097 , 0.98666604, 0.81290687, 0.94290781])

In [ ]:
a=np.random.random((4,5))
a

array([[0.04839667, 0.71206574, 0.98666604, 0.42893164, 0.42222836],
       [0.17614512, 0.9286097 , 0.85695847, 0.74918948, 0.86475693],
       [0.9916884 , 0.49818044, 0.27300795, 0.47456811, 0.94290781],
       [0.51804393, 0.81190884, 0.19072869, 0.81290687, 0.01721512]])

In [ ]:
a.max(axis=1)

array([0.98666604, 0.9286097 , 0.9916884 , 0.81290687])

In [ ]:
a.argmax(axis=1)

array([2, 1, 0, 3])

In [ ]:
a.argmax(axis=0)

array([2, 1, 0, 3, 2])

# Lab-Placeholders and simple functions

In [ ]:
eq_array=np.linspace(0,1,50)
eq_array

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [ ]:
eq_array=eq_array.reshape(5,10)
eq_array

array([[0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
        0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347],
       [0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
        0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ],
       [0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
        0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673],
       [0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
        0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837],
       [0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
        0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]])

In [ ]:
ran=np.random.random(50)
ran

array([0.92470215, 0.65854117, 0.55711707, 0.13159362, 0.37574594,
       0.45067911, 0.03893438, 0.54192101, 0.47355891, 0.54785413,
       0.56632593, 0.72955195, 0.14820375, 0.55408583, 0.30435468,
       0.405468  , 0.03714372, 0.26626686, 0.81197068, 0.8302673 ,
       0.93699694, 0.63207073, 0.40806171, 0.47901443, 0.5436651 ,
       0.19393426, 0.81029043, 0.30093629, 0.62101155, 0.11049605,
       0.84032798, 0.17984909, 0.76227276, 0.70945248, 0.08770469,
       0.48721663, 0.34136109, 0.52392992, 0.94138868, 0.75165649,
       0.40986478, 0.92133664, 0.05656824, 0.00519472, 0.92660941,
       0.67316976, 0.08210779, 0.39733301, 0.04443711, 0.72782858])

In [ ]:
ran=ran.reshape(5,-1)
ran

array([[0.92470215, 0.65854117, 0.55711707, 0.13159362, 0.37574594,
        0.45067911, 0.03893438, 0.54192101, 0.47355891, 0.54785413],
       [0.56632593, 0.72955195, 0.14820375, 0.55408583, 0.30435468,
        0.405468  , 0.03714372, 0.26626686, 0.81197068, 0.8302673 ],
       [0.93699694, 0.63207073, 0.40806171, 0.47901443, 0.5436651 ,
        0.19393426, 0.81029043, 0.30093629, 0.62101155, 0.11049605],
       [0.84032798, 0.17984909, 0.76227276, 0.70945248, 0.08770469,
        0.48721663, 0.34136109, 0.52392992, 0.94138868, 0.75165649],
       [0.40986478, 0.92133664, 0.05656824, 0.00519472, 0.92660941,
        0.67316976, 0.08210779, 0.39733301, 0.04443711, 0.72782858]])

In [ ]:
out=eq_array*ran
out

array([[0.        , 0.01343962, 0.02273947, 0.00805675, 0.03067314,
        0.04598766, 0.00476748, 0.07741729, 0.07731574, 0.10062627],
       [0.11557672, 0.16377697, 0.0362948 , 0.14700236, 0.08695848,
        0.12412286, 0.01212856, 0.0923783 , 0.29827495, 0.32194038],
       [0.38244773, 0.27088746, 0.18321138, 0.22484351, 0.26628495,
        0.09894605, 0.42995002, 0.16582204, 0.35486374, 0.06539562],
       [0.51448652, 0.11378208, 0.49781078, 0.47779453, 0.06085631,
        0.34801188, 0.2507959 , 0.39562055, 0.73005653, 0.59825721],
       [0.3345835 , 0.77091433, 0.04848706, 0.00455863, 0.83205743,
        0.61821712, 0.07708079, 0.38111534, 0.04353023, 0.72782858]])

In [ ]:
#get index of max element in each row
out.argmax(axis=1)

array([9, 9, 6, 8, 4])

In [ ]:
#Get min value in each column
out.min(axis=0)

array([0.        , 0.01343962, 0.02273947, 0.00455863, 0.03067314,
       0.04598766, 0.00476748, 0.07741729, 0.04353023, 0.06539562])

# Reversing of arrays

In [ ]:
a=np.array([12,9,8,14,56])
a

array([12,  9,  8, 14, 56])

In [ ]:
b=np.flip(a)
b

array([56, 14,  8,  9, 12])

In [ ]:
b=a[::-1]
b

array([56, 14,  8,  9, 12])

# Sorting of array

In [ ]:
a=np.array([[12,66],[34,23]])
a

array([[12, 66],
       [34, 23]])

In [ ]:
arr1=np.sort(a,axis=1)
arr1

array([[12, 66],
       [23, 34]])

In [ ]:
arr1=np.sort(a,axis=0)
arr1

array([[12, 23],
       [34, 66]])

# Stacking of two arrays

In [ ]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [ ]:
c=np.concatenate((a,b),axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
c=np.concatenate((a,b),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])