<a href="https://colab.research.google.com/github/tariqzia5/Python_P/blob/main/Tariq_Zia_Python_Project_Assignment1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Create a 1D array of numbers from -5 to 5
Desired output: array([-5, -4, -3,-2,-1,0, 1, 2, 3, 4, 5])

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([-5,-4,-3,-2,-1,0,1,2,3,4,5])
arr1

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

# 2.Find the maximum element in a 2D array.

arr = np.array([[1, 2, 3], [4, 5, 6]])

Output: 6

In [ ]:
arr=np.array([[1, 2, 3],[4, 5, 6]])

In [ ]:
arr.max()

6

# 3.Extract all odd numbers from items_array

items_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 Desired output:array([1, 3, 5, 7, 9])

In [ ]:
a=np.array([0,1,2,3,4,5,6,7,8,9])
for i in a:
    if i%2==1:
        print(i)

1
3
5
7
9


In [ ]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

In [ ]:
odd=np.where(a%2==1)
odd

(array([1, 3, 5, 7, 9]),)

# 4.Convert a 1D array to a 2D array with 2 rows

Input: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:
 array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a=np.array([0,1,2,3,4,5,6,7,8,9])

In [ ]:
2_d=np.reshape()

#5.Raise each element in a 1D array to the power of a scalar. 
arr = np.array([1, 2, 3])

scalar = 2

Output: [1 4 9]

#6.stack two arrays vertically

Input:

a= array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

b= array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])


Desired Output:

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [ ]:
a=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

b=np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [ ]:
c=np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
b = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
stacked_array = np.concatenate((a, b), axis=0)
stacked_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# 7.Set all elements in a 2D array that are greater than a value to 0, and all other elements to 1.


arr = np.array([[1, 2, 3], [4, 5, 6]])

value = 3

Output: [[1 1 1] [0 0 0]]

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
value=3
a=np.where(arr>3,0,1)
a

array([[1, 1, 1],
       [0, 0, 0]])

In [ ]:
a=

#8.Create an array of all ones with shape (2, 3)
Output: [[1. 1. 1.] [1. 1. 1.]]

In [ ]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

#9.Find the transpose of a 2D array.

arr = np.array([[1, 2, 3], [4, 5, 6]])

Output: [[1 4] [2 5] [3 6]]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
t=np.transpose(arr)
t

array([[1, 4],
       [2, 5],
       [3, 6]])

#10.Get the common items between two python numpy arrays?

Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:
array([2, 4])

In [ ]:
 a=np.array([1,2,3,2,3,4,3,4,5,6])
 b=np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
c=np.intersect1d(a,b)
c

array([2, 4])

# 11.Find the Average of a 1D array.

arr = np.array([1, 2, 3])

Output: 2.0

In [ ]:
arr = np.array([1, 2, 3])

In [ ]:
b=np.average(arr)
b

2.0

# 12.Get the positions where elements of a and b match

Input:

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

array([1, 3, 5, 7])

In [ ]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(a==b)
c

(array([1, 3, 5, 7]),)

#13 Create a 2D array of zeros with shape (3, 4).

Output: [[0. 0. 0. 0.] [0. 0. 0. 0.] [0. 0. 0. 0.]]


In [ ]:
import numpy as np

In [ ]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#14.Get all items between 5 and 10 from a

Input:
a = np.array([2, 6, 1, 9, 10, 3, 27])

Desired Output:
(array([6, 9, 10]),)

In [ ]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a

array([ 2,  6,  1,  9, 10,  3, 27])

In [ ]:
b=np.where((a >=5) & (a <=10))
b

(array([1, 3, 4]),)

In [ ]:
values=a[b]
values

array([ 6,  9, 10])

#15.Create a 1D array with 10 equally spaced values between 1 and 100.

Output: [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]

In [ ]:
a=np.linspace(1,100,10)
a

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

#16.Print only 3 decimal places in python numpy array?

Input:
rand_arr = np.random.random((5,3))

In [ ]:
rand_arr = np.random.random((5,3))
rand_arr

array([[0.52404281, 0.9784001 , 0.78259713],
       [0.08417821, 0.09905565, 0.68558593],
       [0.51392407, 0.46982971, 0.72663378],
       [0.47208586, 0.03371525, 0.43726789],
       [0.32552056, 0.1412437 , 0.2009467 ]])

In [ ]:
a=np.round(rand_arr,3)
a

array([[0.524, 0.978, 0.783],
       [0.084, 0.099, 0.686],
       [0.514, 0.47 , 0.727],
       [0.472, 0.034, 0.437],
       [0.326, 0.141, 0.201]])

#17.Replace all values greater than a given value to a given cutoff?

a = np.random.uniform(1,50, 20)

From the array a, replace all values greater than 30 to 30 and less than 10 to 10.


In [ ]:
a = np.random.uniform(1,50, 20)
a

array([27.66103021, 16.36109354, 33.87551082, 24.32233398, 39.52467493,
       46.33499782, 12.08966898,  7.72150743, 43.90797482, 28.53609231,
       42.49762824, 35.98780609, 44.99479413, 13.4398275 , 44.25311739,
       48.4751369 , 17.66957086, 26.51768804, 20.82198953, 23.20435883])

In [ ]:
a = np.random.uniform(1,50, 20)
lim_h=30
lim_l=10
b=np.where(a>lim_h,lim_h,np.where(a<lim_l,lim_l,a))
b

array([30.        , 30.        , 30.        , 30.        , 10.        ,
       14.87522617, 15.85450756, 21.27208481, 28.89811227, 10.83479017,
       26.58864504, 10.        , 30.        , 23.66447649, 14.27737041,
       10.        , 10.        , 30.        , 30.        , 10.        ])

# 18.Get the positions of top 5 maximum values in a given array a.

a = np.random.uniform(1,50, 20)

In [ ]:
a = np.random.uniform(1,50, 20)
a

array([23.56241098, 47.91260226, 12.3222348 , 47.32389582, 49.00365332,
       39.77663426, 26.89434442, 36.06002603, 17.71487463,  4.97608616,
       40.80829735, 45.03288179,  3.03968421, 12.88362781, 46.52635846,
        5.26105354,  5.81559474, 32.2320325 , 22.1618694 , 46.27501917])

In [ ]:
b=a.top(5)
b        

AttributeError: ignored

In [ ]:
a = np.random.uniform(1,50, 20)
sorted_a=np.sort(a)[::-1]
sorted_a



array([44.70706805, 44.15912275, 39.94796586, 38.92831001, 35.27197134,
       34.7791974 , 34.57457401, 31.76886644, 30.60555269, 30.38168508,
       25.06726469, 17.5322963 , 16.77552712, 13.63700585, 11.41906419,
        7.3046739 ,  7.0494766 ,  6.50939624,  5.50729753,  4.34473477])

In [ ]:
a = np.random.uniform(1,50, 20)
a

array([ 9.8764727 , 48.60925536, 22.7080111 , 31.07226935,  3.51728631,
       18.49260331, 41.88895453, 23.09770512, 26.13394878, 44.21763858,
        3.38054287,  7.06735134, 37.47564671,  4.6340543 , 47.69455043,
       49.04775867, 28.65819254, 17.51906378, 29.7878832 , 27.95558094])

#19.Create a 2D array with random values between 0 and 1 with shape (3, 3).

Sample Output: 

[[0.34793787 0.85788454 0.98636123] [0.05243493 0.17497094 0.53942809] [0.81386678 0.11992322 0.42892938]]

# 20.Compute the maximum for each row in the given array a.

a = np.random.randint(1,10, [5,3])

In [ ]:
a = np.random.randint(1,10, [5,3])
a

array([[1, 4, 7],
       [9, 5, 8],
       [2, 4, 5],
       [7, 8, 4],
       [4, 8, 3]])

In [ ]:
b=np.amax(a,axis=1)
b

array([7, 9, 5, 8, 8])

In [ ]:
a = np.random.randint(1,10, [5,3])
n=np.apply_along_axis(max,axis=1,arr=a)
n

array([8, 8, 9, 6, 7])

#21.Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False 

a = np.random.randint(0, 5, 10)

In [ ]:
a=np.random.randint(0, 5, 10)
a

array([2, 4, 2, 3, 1, 1, 0, 0, 3, 0])

In [ ]:
import numpy as np

#22.Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [ ]:
a=np.arange(5,5+10*3,3)
a

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

#23.Find the indices of all maximum elements in a 1D array.

arr = np.array([1, 3, 2, 3, 4, 3])

Output: [[4]]

In [ ]:
arr = np.array([1, 3, 2, 3, 6, 3])
b=arr.max()
b

6

In [ ]:
arr = np.array([1, 3, 2, 3, 6, 3])
b=np.max(arr)
b

6

In [ ]:
=

#24.Create the ranks for the given numeric array a

Input:

np.random.seed(10)

a = np.random.randint(20, size=10)

Desired output:

[4 2 6 0 8 7 9 3 5 1]


#25.Concatenate two 1D arrays horizontally.
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

Output: [1 2 3 4 5 6]